from valida import *
def test_usuario():
    assert usuario("fernando") =="f"
    assert usuario("Fernando") =="c"
    assert senha("fernando") =="f"
    assert senha("Fernando") =="f"
    assert senha("Feeeernando1") =="f"
    assert senha("@@@@@@@@@@@") =="f"
    assert senha("222222222222") =="f"
    assert senha("fernando9") =="f"
    assert senha("fer nando2") =="f"
    assert senha("fernando2") =="f"
    assert senha("Fernandooooo3") =="f"
    assert senha("Fernando$$123") =="c"
    assert limite("@@@@@@@@@@@@@") =="c"
    assert limite("fernando6677") =="c"
    assert senha("FERNANDO#####@@@1234556778900SJBDASOIFSGFISSGDFIDSSFSDF") =="f"